version: "3.8"

services:
  backend:
    build: .
    container_name: pengalaman_backend_app
    restart: always
    volumes:
      - ./public/uploads:/app/public/uploads
    ports:
      - "3006:3006"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: namadb

  db:
    image: postgres:16
    container_name: pengalaman_postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: namadb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
