version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expressjs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: expressjs
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/expressjs_db?schema=public"
    depends_on:
      - db
    ports:
      - "3001:3001"
    command: npm run dev
volumes:
  postgres_data:
